// Writes the bundled synthetic datasets to data/*.json so they can be inspected without a browser.
// The lesson itself reads data.js directly; these files are documentation, regenerated by `npm run export-data`.
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
require('../data.js');
const D = globalThis.DD_DATA;
writeFileSync(new URL('../data/framing.json', import.meta.url), JSON.stringify(D.framing, null, 1));
writeFileSync(new URL('../data/population.json', import.meta.url), JSON.stringify({ seed: D.seeds.population, generator: 'data.js buildPopulation (mulberry32 + Box-Muller)', students: D.population }, null, 0));
writeFileSync(new URL('../data/weeks.json', import.meta.url), JSON.stringify({ seed: D.seeds.weeks, generator: 'data.js buildWeeks (mulberry32 + Box-Muller)', weeks: D.weeks }, null, 1));
console.log(`exported framing (${D.framing.terms.length} terms), population (${D.population.length} students), weeks (${D.weeks.length} weeks)`);
